% Contains all the Global variables for RSS trace collection
% 
% Author: Sanjib Sur
% Institute: University of Wisconsin - Madison
% Version: 0.0.1
% Last modified: 08/02/2014
% 
% Comments: This file contains all the global variables used across
% different files and functions of the RSS trace collection and process
% 

global DEBUG_ON trace_folder trace_file_name ...
    trace_file_handle trace_packet_count trace_packet_removal_cnt ...
    rss_win_size rss_envelope_size result_file_name result_file_handle...
    WARPLab_RF_RX WARPLab_node_rx WARPLab_rxLength WARPLab_eth_trig ...
    WARPLab_RF_TX WARPLab_node_tx WARPLab_txLength ...
    azi_angle_resolution azi_max_angle azi_min_angle ...
    elev_angle_resolution elev_max_angle elev_min_angle ...
    dev_id_azi dev_id_elev sport_default_params serial_obj_azi ...
    serial_obj_elev packet_per_resolution rss_heatmap;